spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    storage_engine: innodb
  session:
    store-type: jdbc
  logging:
    level:
      org.hibernate.SQL: debug